# Generated by Django 4.2.4 on 2023-08-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="byline",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("story", "story"),
                    ("review", "review"),
                    ("news", "news"),
                    ("snack-bar", "snack-bar"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="head_article_byline_widescreen_margin",
            field=models.CharField(default="0", max_length=4),
        ),
        migrations.AddField(
            model_name="post",
            name="imagesmall",
            field=models.ImageField(default="", upload_to="parking_pics"),
        ),
        migrations.AddField(
            model_name="post",
            name="imagewide",
            field=models.ImageField(default="", upload_to="parking_pics"),
        ),
        migrations.AddField(
            model_name="post",
            name="park_destination",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="park_difficulty",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="park_restrictions",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="park_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="review_location",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="review_restrictions",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="review_snackbar_status",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="review_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default=""),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=100),
        ),
    ]
